services:
  app:
    build: .
    container_name: diamond-app
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: diamond_inventory
      PORT: 3001
    volumes:
      - ./excel:/app/excel
      - frontend_dist:/app/frontend-dist
    networks:
      - web-network
    restart: always

volumes:
  frontend_dist:

networks:
  web-network:
    external: true
